name: "ğŸ› Bug"
description: é—®é¢˜æŠ¥å‘Š.
title: "ğŸ› [BUG] <é—®é¢˜æ ‡é¢˜>"
labels: [
  "bug"
]

body:
  - type: textarea
    id: description
    attributes:
      label: "é—®é¢˜æè¿°"
      description: è¯·è¾“å…¥ç®€æ´ä¸”æ˜ç¡®çš„é—®é¢˜æè¿°ã€‚
      placeholder: ...çš„...åŠŸèƒ½å‡ºç°...å¼‚å¸¸
    validations:
      required: true
  
  - type: textarea
    id: repord
    attributes:
      label: "å¤ç°æ­¥éª¤"
      description: è¾“å…¥ç®€æ˜çš„é—®é¢˜å¤ç°æ­¥éª¤ã€‚
      value: |
        åœ¨xxxxä¸Šxxxå¯¼è‡´xxx...
      render: bash
    validations:
      required: false
  
  - type: textarea
    id: screenshot
    attributes:
      label: "é—®é¢˜æˆªå›¾"
      description: æ·»åŠ é—®é¢˜æˆªå›¾ä»¥ä¾¿æˆ‘ä»¬å¿«é€Ÿå®šä½.
      value: |
        ![å›¾ç‰‡æ³¨é‡Š](å›¾ç‰‡é“¾æ¥)
    validations:
      required: false
